---
title: "Eurostat masterfile"
author: "Jonas Rekdal Mathisen"
date: "30/12/2021"
output: html_document
---

```{r setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(devtools, countrycode, eurostat, reactable, tidyverse)

```

#Introduction
* https://kpj.github.io/mining_visualization/Eurostat_Visualizations.html
* 

#Packages
```{r}
pacman::p_load(devtools, countrycode, eurostat, reactable, tidyverse)

#Evaluate adding:
  #https://ropengov.github.io/giscoR/

#Documentation Eurostat
  #https://cran.r-project.org/web/packages/eurostat/eurostat.pdf

```

#Retrieving geographical information

```{r geo}

#Our countries
NPI_countries <- IndData %>% select(c("UnitName", "UnitCode"))

#Eurostat countries

```

#Datasets relevant for NOURISHING

```{r}

#https://ec.europa.eu/eurostat/web/health/data/database

#https://ec.europa.eu/eurostat/web/health/data/main-tables

test1 <- "TESSI190"
test2 <- c("hlth_ehis_bm1e", "hlth_dpe010")

GeneralVariables <- c(
  "hlth_ehis_bm1e", #Body Mass Index (no kids) #OK
  "hlth_dpe010", #Risk of poverty or social exclusion rate #OK
  "ilc_di11", #Income quintile ratio S80/20 for disposable income
  "TESSI190", #Gini coefficient
  "sdg_03_20", #Share of people with good or very good percieved health
  "sdg_03_42", #Standardised preventable and treatable mortality
  "HLTH_EHIS_MH1E" #Current depressive symptoms
)

NOURISHING_context <- c(
  "hlth_cfv", #Consumption of fruits and vegetables
  "PRC_FSC_IDX",#Food price monitoring tool
  "prc_hicp", #Harmonised index of consumer prices
  "SDG_02_40", #Area under organic farming
  "PRC_PPP_IND", #Purchasing power parities (PPPs): ref food, fruit, fish, veggies
  "nama_10_co3_p3", #Final consumption expenditure of households (Food and non alcoholic beverages) 
  "GOV_10A_TAXAG" #% GDP in excise duties and consumption taxes 
)

#Data relevant for NOURISHING but not on Eurostat
NOURISHING_WHO <- c(
  "", #proportion of obese persons among aged 18 years and under 
  "", #proportion of obese persons among aged 18 years and over
)
```
#Retrieving data from Eurostat

```{r}
df_list <- c()
meta_list <- c()

#Switch "test" with other vectors
for (dataset in test2){
  #Get name of dataframe
  dataset_name <- eurostat::label_eurostat_tables(dataset)
  print(dataset_name)
  
  #Retrieve data in raw format, evaluate time_format=num
  df_data <- eurostat::get_eurostat(dataset, time_format = "raw")
  df_data <- eurostat::label_eurostat(df_data, code = df_data$geo, fix_duplicated=TRUE)
  
  
}hlth_ehis_bm1e
  
dataset_name <- eurostat::label_eurostat_tables(test2)

x <- search_eurostat("hlth_ehis_bm1e")

hlth_ehis_bm1e <- eurostat::get_eurostat("hlth_ehis_bm1e")

hlth_ehis_bm1e <- eurostat::get_eurostat(hlth_ehis_bm1e, time_format = "num")

df_data <- eurostat::label_eurostat(df_data, code = df_data$geo, fix_duplicated=TRUE)


dataset_name
```
```{r}
search_eurostat("BMI")
```

